# NovaiOS Calamares settings — which modules to run, in order
---
modules-search: local

sequence:
  - show:
      - welcome
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - packages
      - luksbootkeyfile
      - plymouthcfg
      - initramfs
      - removeuser
      - initcpiocfg
      - initcpio
  - show:
      - finished

branding: novaios

prompt-install: false

dont-chroot: false
